[unstable]
# Requires the rust-src component. `rustup +nightly component add rust-src`
build-std = ["std", "panic_abort"]
# https://github.com/rust-lang/rust/issues/107016
# build-std-features = ["panic_immediate_abort"]